name: Test
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
      - name: Rubocop
        run: bundle exec rubocop
      - name: Setup test database
        run: bin/rails db:setup
      - name: Run tests
        run: bin/rspec